services:

  db:
    image: postgres:alpine3.18
    user: postgres
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q" ]
      retries: 3
      timeout: 45s
      interval: 10s

  cache:
    restart: always
    image: redis:alpine3.18
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 45s
      interval: 10s

  web:
    restart: always
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
